#!/usr/bin/env python3
# vim: ts=4 expandtab

from __future__ import annotations

import json
import pkgutil
import importlib

from datetime import date
from os import chdir
from os.path import dirname, exists

from catz.ui import Window
from catz import get_data_object, page_list


def main(today: date):


    ###
    # Load in all the plugins
    ###
    for package in pkgutil.iter_modules(['./plugins'], 'plugins.'):
        importlib.import_module(package.name)

    ###
    # Generate the data
    ###
    CatZ = get_data_object()
    catz = CatZ()

    ###
    # Load any existing data.
    ###
    ofile: str = 'data/%04d-%02d-%02d.json' % (today.year, today.month, today.day)

    try:
        if exists(ofile):
            with open(ofile, 'r') as in_stream:
                json_blob = json.load(in_stream)

            catz = CatZ.from_json(json_blob)
    except json.decoder.JSONDecodeError:
        pass

    with Window() as window:
        try:
            for page in page_list():
                window.reset(page.title())
                page.query(window, catz)
        except KeyboardInterrupt:
            pass

    with open(ofile, 'w') as out_stream:
        json.dump(catz.to_json(), out_stream)


if __name__ == '__main__':
    chdir(dirname(__file__))
    main(date.today())
